### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [theMesox/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [ ] Rename repository to **oop-put-course**
- [ ] Format code properly

**Task 2**
- [ ] Code doesn't compile 😢
